os: osx
language: node_js
node_js:
  - '12'
  - '10'
  - '8'
before_script:
  - npm run lint
  - npm run build
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
